# -*- coding: utf-8 -*-

"""
    pepipost

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

from pepipost.api_helper import APIHelper


class Configuration(object):

    """A class used for configuring the SDK by a user.

    This class need not be instantiated and all properties and methods
    are accessible without instance creation.

    """

    # Set the array parameter serialization method
    # (allowed: indexed, unindexed, plain, csv, tsv, psv)
    array_serialization = "indexed"

    # An enum for SDK environments
    class Environment(object):
        PRODUCTION = 0

    # An enum for API servers
    class Server(object):
        SERVER1 = 0
        PEPI_1 = 1

    # The environment in which the SDK is running
    environment = Environment.PRODUCTION

    # Your Pepipost API Key. You will find the api key in the Pepipost
    # application in Integrations.
    api_key = 'SGVsbG8gd2VsY29tZSB0byBQRVB'


    # All the environments the SDK can run in
    environments = {
        Environment.PRODUCTION: {
            Server.SERVER1: 'http://apiuk-lb3.falconide.com/v5/mail',
            Server.PEPI_1: 'https://api.pepipost.com/v5/mail',
        },
    }

    @classmethod
    def get_base_uri(cls, server=Server.SERVER1):
        """Generates the appropriate base URI for the environment and the server.

        Args:
            server (Configuration.Server): The server enum for which the base URI is required.

        Returns:
            String: The base URI.

        """
        return cls.environments[cls.environment][server]
