# -*- coding: utf-8 -*-

"""
    pepipost

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

from pepipost.decorators import lazy_property
from pepipost.configuration import Configuration
from pepipost.controllers.send_controller import SendController


class PepipostClient(object):

    config = Configuration

    @lazy_property
    def send(self):
        return SendController()


    def __init__(self,
                 api_key='SGVsbG8gd2VsY29tZSB0byBQRVB'):
        if api_key is not None:
            Configuration.api_key = api_key

